### ISSUE TITLE
export glb file without it's texture 

### ISSUE THREAD

**Issue by donatellofang** [SapwoodStudio/Transmogrifier#8]
My glb model file has a texture which uv is unwraped,the tool didn't export the texture but the preview texture.That's not predicted

**Comment by SapwoodStudio** [comment]
Hi, @donatellofang, sorry to hear it didn't work the way you expected.  Would you share a screenshot of your Transmogrifier settings?  If you are converting from a GLB and your textures are packed inside, did you change the Textures>Source to "Packed"?
